1. Write a Python Program to Add Two Matrices?

In [8]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[6,7,8],
            [1,2,3]])
c=a+b
print("The addition of matrix is:")
print(c)

The addition of matrix is:
[[ 7  9 11]
 [ 5  7  9]]


2. Write a Python Program to Multiply Two Matrices?

In [9]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
c=a.dot(b)
print("The multiplication of matrix is:")
print(c)

The multiplication of matrix is:
[[19 22]
 [43 50]]


3. Write a Python Program to Transpose a Matrix?

In [10]:
a=np.array([[1,2,3],
            [4,5,6]])
a=a.transpose()
print("The transpose of the matrix")
print(a)

The transpose of the matrix
[[1 4]
 [2 5]
 [3 6]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [11]:
words = ['welcome','to','FSDS','2.0']
words.sort()
print(words)

['2.0', 'FSDS', 'to', 'welcome']


5. Write a Python Program to Remove Punctuation From a String?

In [7]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello, world!!!, This code is written in python(3.8) !!!"
new_str = ""
for str in my_str:
    if str not in punctuations:
        new_str += str
print(new_str)

Hello world This code is written in python38 
